language: python
sudo: required

matrix:
  include:
    - python: 2.7
      env: NUMPY=1.9 SCIPY=0.15 CYTHON=0.22
      
before_install:
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update -q --yes conda
  - conda info -a

install:
  - conda create -q --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install -q --yes numpy=$NUMPY scipy=$SCIPY cython=$CYTHON
  - python setup.py install

script:
  - nosetests tests -v
